[project]
name = "pylearn"
version = "0.1.0"
description = "pylearn project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.1.0",
    "langchain-openai>=1.1.0",
    "langgraph>=1.0.4",
    "notebook>=7.4.7",
    "pydantic>=2.11.10",
    "python-dotenv>=1.2.1",
]
